substitutions:
  device_name: slimmelezer
  friendly_name: DSMR Reader

external_components:
  - source: github://geduxas/esphome-dsmr-eso@main
    refresh: 0s

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini
  name_add_mac_suffix: false
  project:
    name: geduxas.esodsmr
    version: "2.0"

wifi:
  # remove leading '#' and fill in your wifi details
  ssid: !secret wifi_ssid 
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}

captive_portal:

# Enable logging
logger:
  baud_rate: 0
  level: WARN

# Enable Home Assistant API
api:

ota:

#dashboard_import:
#  package_import_url: github://geduxas/esphome-dsmr-eso/slimmelezer.yaml@main
#  import_full_config: true

web_server:
  port: 80

uart:
  baud_rate: 115200
  rx_pin: D7
  rx_buffer_size: 3072

dsmr_eso:
  id: dsmr_instance
  max_telegram_length: 4096
  # For Luxembourg users set here your decryption key
  #decryption_key: !secret decryption_key // enable this when using decryption for Luxembourg; key like '00112233445566778899AABBCCDDEEFF'
